name: Build and Deploy to Cloud Run


on:
  push:
    branches:
      - Main

env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  RUN_REGION: us-central1
  SERVICE_NAME: helloworld-python

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v0
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.RUN_SA_KEY }}
          project_id: ${{ secrets.RUN_PROJECT }}
          export_default_credentials: true

      - name: Maven package
        run: mvn package

      - name: deploy cloud function
        uses: google-github-actions/deploy-cloud-functions@v0.1.0
        with:
          name: HttpCloudFunction
          runtime: java11
          project_id: ${{ secrets.RUN_PROJECT }}
          entry_point: functions.HttpCloudFunction

#    - name: Docker Configure
#      run: gcloud auth configure-docker gcr.io
#
#    # Build and push image to Google Container Registry
#    - name: Build
#      run: |-
#        gcloud builds submit \
#          --quiet \
#          --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"
#    # Deploy image to Cloud Run
#    - name: Deploy
#      run: |-
#        gcloud run deploy "$SERVICE_NAME" \
#          --quiet \
#          --region "$RUN_REGION" \
#          --image "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
#          --platform "managed" \
#          --allow-unauthenticated
